// Code generated by "stringer -type=BasisStatus"; DO NOT EDIT.

package highs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownBasisStatus-0]
	_ = x[Lower-1]
	_ = x[Basic-2]
	_ = x[Upper-3]
	_ = x[Zero-4]
	_ = x[NonBasic-5]
}

const _BasisStatus_name = "UnknownBasisStatusLowerBasicUpperZeroNonBasic"

var _BasisStatus_index = [...]uint8{0, 18, 23, 28, 33, 37, 45}

func (i BasisStatus) String() string {
	if i < 0 || i >= BasisStatus(len(_BasisStatus_index)-1) {
		return "BasisStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BasisStatus_name[_BasisStatus_index[i]:_BasisStatus_index[i+1]]
}
