#! /usr/bin/env python3

####################################################
# Generate extern declarations from highs_c_api.h. #
#                                                  #
# Author: Scott Pakin <pakin@lanl.gov>             #
####################################################

import re
import subprocess
import sys


def abend(msg):
    'Abort the program with an error message.'
    sys.stderr.write('gen-externs: %s\n' % msg)
    sys.exit(1)


def preprocess_header(cpp_flags):
    'Run interfaces/highs_c_api.h through the C preprocessor.'
    proc = subprocess.Popen(['cpp'] + cpp_flags + ['-E', '-'],
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE,
                            text=True)
    stdout, stderr = \
        proc.communicate(input='#include <interfaces/highs_c_api.h>')
    if stderr != '':
        abend(stderr)
    return stdout


def output_header_boilerplate():
    'Output some header boilerplate code.'
    print('''\
/*
 * Code generated by gen-externs.py.  DO NOT EDIT.
 *
 * This file declares extern all of the HiGHS constants needed by the
 * highs package.  It is required because HiGHS declares all constants
 * with global scope (const) rather than with file scope (static const).
 */

#ifndef _EXTERNS_H_
#define _EXTERNS_H_

#include <lp_data/HighsCallbackStruct.h>
#include <util/HighsInt.h>
''')


def output_constants(code):
    'Output constant definitions found in the code.'
    const_re = re.compile(r'^(const[\s\w*]+\w)\s+=.*?;\s*$', re.MULTILINE)
    for const_def in const_re.finditer(code):
        print('extern %s;' % const_def[1])


def output_functions(code):
    'Output function declarations found in the code.'
    func_re = re.compile(r'^(\w[\w\s*]+\sHighs_\w+\(.*?\);)\s*$',
                         re.MULTILINE | re.DOTALL)
    for func_def in func_re.finditer(code):
        print('extern\n%s\n' % func_def[1])


def output_footer_boilerplate():
    'Output some footer boilerplate code.'
    print('#endif')


if __name__ == '__main__':
    code = preprocess_header(sys.argv[1:])
    output_header_boilerplate()
    print('/* Constants */')
    output_constants(code)
    print('')
    print('/* Functions */')
    output_functions(code)
    output_footer_boilerplate()
