/*
 * Code generated by gen-externs.py.  DO NOT EDIT.
 *
 * This file declares extern all of the HiGHS constants needed by the
 * highs package.  It is required because HiGHS declares all constants
 * with global scope (const) rather than with file scope (static const).
 */

#ifndef _EXTERNS_H_
#define _EXTERNS_H_

#include <lp_data/HighsCallbackStruct.h>
#include <util/HighsInt.h>

/* Constants */
extern const HighsInt kHighsMaximumStringLength;
extern const HighsInt kHighsStatusError;
extern const HighsInt kHighsStatusOk;
extern const HighsInt kHighsStatusWarning;
extern const HighsInt kHighsVarTypeContinuous;
extern const HighsInt kHighsVarTypeInteger;
extern const HighsInt kHighsVarTypeSemiContinuous;
extern const HighsInt kHighsVarTypeSemiInteger;
extern const HighsInt kHighsVarTypeImplicitInteger;
extern const HighsInt kHighsOptionTypeBool;
extern const HighsInt kHighsOptionTypeInt;
extern const HighsInt kHighsOptionTypeDouble;
extern const HighsInt kHighsOptionTypeString;
extern const HighsInt kHighsInfoTypeInt64;
extern const HighsInt kHighsInfoTypeInt;
extern const HighsInt kHighsInfoTypeDouble;
extern const HighsInt kHighsObjSenseMinimize;
extern const HighsInt kHighsObjSenseMaximize;
extern const HighsInt kHighsMatrixFormatColwise;
extern const HighsInt kHighsMatrixFormatRowwise;
extern const HighsInt kHighsHessianFormatTriangular;
extern const HighsInt kHighsHessianFormatSquare;
extern const HighsInt kHighsSolutionStatusNone;
extern const HighsInt kHighsSolutionStatusInfeasible;
extern const HighsInt kHighsSolutionStatusFeasible;
extern const HighsInt kHighsBasisValidityInvalid;
extern const HighsInt kHighsBasisValidityValid;
extern const HighsInt kHighsPresolveStatusNotPresolved;
extern const HighsInt kHighsPresolveStatusNotReduced;
extern const HighsInt kHighsPresolveStatusInfeasible;
extern const HighsInt kHighsPresolveStatusUnboundedOrInfeasible;
extern const HighsInt kHighsPresolveStatusReduced;
extern const HighsInt kHighsPresolveStatusReducedToEmpty;
extern const HighsInt kHighsPresolveStatusTimeout;
extern const HighsInt kHighsPresolveStatusNullError;
extern const HighsInt kHighsPresolveStatusOptionsError;
extern const HighsInt kHighsPresolveStatusOutOfMemory;
extern const HighsInt kHighsModelStatusNotset;
extern const HighsInt kHighsModelStatusLoadError;
extern const HighsInt kHighsModelStatusModelError;
extern const HighsInt kHighsModelStatusPresolveError;
extern const HighsInt kHighsModelStatusSolveError;
extern const HighsInt kHighsModelStatusPostsolveError;
extern const HighsInt kHighsModelStatusModelEmpty;
extern const HighsInt kHighsModelStatusOptimal;
extern const HighsInt kHighsModelStatusInfeasible;
extern const HighsInt kHighsModelStatusUnboundedOrInfeasible;
extern const HighsInt kHighsModelStatusUnbounded;
extern const HighsInt kHighsModelStatusObjectiveBound;
extern const HighsInt kHighsModelStatusObjectiveTarget;
extern const HighsInt kHighsModelStatusTimeLimit;
extern const HighsInt kHighsModelStatusIterationLimit;
extern const HighsInt kHighsModelStatusUnknown;
extern const HighsInt kHighsModelStatusSolutionLimit;
extern const HighsInt kHighsModelStatusInterrupt;
extern const HighsInt kHighsBasisStatusLower;
extern const HighsInt kHighsBasisStatusBasic;
extern const HighsInt kHighsBasisStatusUpper;
extern const HighsInt kHighsBasisStatusZero;
extern const HighsInt kHighsBasisStatusNonbasic;
extern const HighsInt kHighsCallbackLogging;
extern const HighsInt kHighsCallbackSimplexInterrupt;
extern const HighsInt kHighsCallbackIpmInterrupt;
extern const HighsInt kHighsCallbackMipSolution;
extern const HighsInt kHighsCallbackMipImprovingSolution;
extern const HighsInt kHighsCallbackMipLogging;
extern const HighsInt kHighsCallbackMipInterrupt;
extern const HighsInt kHighsCallbackMipGetCutPool;
extern const HighsInt kHighsCallbackMipDefineLazyConstraints;
extern const char* const kHighsCallbackDataOutLogTypeName;
extern const char* const kHighsCallbackDataOutRunningTimeName;
extern const char* const kHighsCallbackDataOutMipNodeCountName;
extern const char* const kHighsCallbackDataOutMipPrimalBoundName;
extern const char* const kHighsCallbackDataOutMipDualBoundName;
extern const char* const kHighsCallbackDataOutMipGapName;
extern const char* const kHighsCallbackDataOutMipSolutionName;
extern const char* const kHighsCallbackDataOutCutpoolNumColName;
extern const char* const kHighsCallbackDataOutCutpoolNumCutName;
extern const char* const kHighsCallbackDataOutCutpoolNumNzName;
extern const char* const kHighsCallbackDataOutCutpoolStartName;
extern const char* const kHighsCallbackDataOutCutpoolIndexName;
extern const char* const kHighsCallbackDataOutCutpoolValueName;
extern const char* const kHighsCallbackDataOutCutpoolLowerName;
extern const char* const kHighsCallbackDataOutCutpoolUpperName;
extern const HighsInt HighsStatuskError;
extern const HighsInt HighsStatuskOk;
extern const HighsInt HighsStatuskWarning;

/* Functions */
extern
HighsInt Highs_lpCall(const HighsInt num_col, const HighsInt num_row,
                      const HighsInt num_nz, const HighsInt a_format,
                      const HighsInt sense, const double offset,
                      const double* col_cost, const double* col_lower,
                      const double* col_upper, const double* row_lower,
                      const double* row_upper, const HighsInt* a_start,
                      const HighsInt* a_index, const double* a_value,
                      double* col_value, double* col_dual, double* row_value,
                      double* row_dual, HighsInt* col_basis_status,
                      HighsInt* row_basis_status, HighsInt* model_status);

extern
HighsInt Highs_mipCall(const HighsInt num_col, const HighsInt num_row,
                       const HighsInt num_nz, const HighsInt a_format,
                       const HighsInt sense, const double offset,
                       const double* col_cost, const double* col_lower,
                       const double* col_upper, const double* row_lower,
                       const double* row_upper, const HighsInt* a_start,
                       const HighsInt* a_index, const double* a_value,
                       const HighsInt* integrality, double* col_value,
                       double* row_value, HighsInt* model_status);

extern
HighsInt Highs_qpCall(
    const HighsInt num_col, const HighsInt num_row, const HighsInt num_nz,
    const HighsInt q_num_nz, const HighsInt a_format, const HighsInt q_format,
    const HighsInt sense, const double offset, const double* col_cost,
    const double* col_lower, const double* col_upper, const double* row_lower,
    const double* row_upper, const HighsInt* a_start, const HighsInt* a_index,
    const double* a_value, const HighsInt* q_start, const HighsInt* q_index,
    const double* q_value, double* col_value, double* col_dual,
    double* row_value, double* row_dual, HighsInt* col_basis_status,
    HighsInt* row_basis_status, HighsInt* model_status);

extern
void* Highs_create(void);

extern
void Highs_destroy(void* highs);

extern
const char* Highs_version(void);

extern
HighsInt Highs_versionMajor(void);

extern
HighsInt Highs_versionMinor(void);

extern
HighsInt Highs_versionPatch(void);

extern
const char* Highs_githash(void);

extern
HighsInt Highs_readModel(void* highs, const char* filename);

extern
HighsInt Highs_writeModel(void* highs, const char* filename);

extern
HighsInt Highs_writePresolvedModel(void* highs, const char* filename);

extern
HighsInt Highs_clear(void* highs);

extern
HighsInt Highs_clearModel(void* highs);

extern
HighsInt Highs_clearSolver(void* highs);

extern
HighsInt Highs_presolve(void* highs);

extern
HighsInt Highs_run(void* highs);

extern
HighsInt Highs_postsolve(void* highs, const double* col_value,
                         const double* col_dual, const double* row_dual);

extern
HighsInt Highs_writeSolution(const void* highs, const char* filename);

extern
HighsInt Highs_writeSolutionPretty(const void* highs, const char* filename);

extern
HighsInt Highs_passLp(void* highs, const HighsInt num_col,
                      const HighsInt num_row, const HighsInt num_nz,
                      const HighsInt a_format, const HighsInt sense,
                      const double offset, const double* col_cost,
                      const double* col_lower, const double* col_upper,
                      const double* row_lower, const double* row_upper,
                      const HighsInt* a_start, const HighsInt* a_index,
                      const double* a_value);

extern
HighsInt Highs_passMip(void* highs, const HighsInt num_col,
                       const HighsInt num_row, const HighsInt num_nz,
                       const HighsInt a_format, const HighsInt sense,
                       const double offset, const double* col_cost,
                       const double* col_lower, const double* col_upper,
                       const double* row_lower, const double* row_upper,
                       const HighsInt* a_start, const HighsInt* a_index,
                       const double* a_value, const HighsInt* integrality);

extern
HighsInt Highs_passModel(void* highs, const HighsInt num_col,
                         const HighsInt num_row, const HighsInt num_nz,
                         const HighsInt q_num_nz, const HighsInt a_format,
                         const HighsInt q_format, const HighsInt sense,
                         const double offset, const double* col_cost,
                         const double* col_lower, const double* col_upper,
                         const double* row_lower, const double* row_upper,
                         const HighsInt* a_start, const HighsInt* a_index,
                         const double* a_value, const HighsInt* q_start,
                         const HighsInt* q_index, const double* q_value,
                         const HighsInt* integrality);

extern
HighsInt Highs_passHessian(void* highs, const HighsInt dim,
                           const HighsInt num_nz, const HighsInt format,
                           const HighsInt* start, const HighsInt* index,
                           const double* value);

extern
HighsInt Highs_passRowName(const void* highs, const HighsInt row,
                           const char* name);

extern
HighsInt Highs_passColName(const void* highs, const HighsInt col,
                           const char* name);

extern
HighsInt Highs_readOptions(const void* highs, const char* filename);

extern
HighsInt Highs_setBoolOptionValue(void* highs, const char* option,
                                  const HighsInt value);

extern
HighsInt Highs_setIntOptionValue(void* highs, const char* option,
                                 const HighsInt value);

extern
HighsInt Highs_setDoubleOptionValue(void* highs, const char* option,
                                    const double value);

extern
HighsInt Highs_setStringOptionValue(void* highs, const char* option,
                                    const char* value);

extern
HighsInt Highs_getBoolOptionValue(const void* highs, const char* option,
                                  HighsInt* value);

extern
HighsInt Highs_getIntOptionValue(const void* highs, const char* option,
                                 HighsInt* value);

extern
HighsInt Highs_getDoubleOptionValue(const void* highs, const char* option,
                                    double* value);

extern
HighsInt Highs_getStringOptionValue(const void* highs, const char* option,
                                    char* value);

extern
HighsInt Highs_getOptionType(const void* highs, const char* option,
                             HighsInt* type);

extern
HighsInt Highs_resetOptions(void* highs);

extern
HighsInt Highs_writeOptions(const void* highs, const char* filename);

extern
HighsInt Highs_writeOptionsDeviations(const void* highs, const char* filename);

extern
HighsInt Highs_getNumOptions(const void* highs);

extern
HighsInt Highs_getOptionName(const void* highs, const HighsInt index,
                             char** name);

extern
HighsInt Highs_getBoolOptionValues(const void* highs, const char* option,
                                   HighsInt* current_value,
                                   HighsInt* default_value);

extern
HighsInt Highs_getIntOptionValues(const void* highs, const char* option,
                                  HighsInt* current_value, HighsInt* min_value,
                                  HighsInt* max_value, HighsInt* default_value);

extern
HighsInt Highs_getDoubleOptionValues(const void* highs, const char* option,
                                     double* current_value, double* min_value,
                                     double* max_value, double* default_value);

extern
HighsInt Highs_getStringOptionValues(const void* highs, const char* option,
                                     char* current_value, char* default_value);

extern
HighsInt Highs_getIntInfoValue(const void* highs, const char* info,
                               HighsInt* value);

extern
HighsInt Highs_getDoubleInfoValue(const void* highs, const char* info,
                                  double* value);

extern
HighsInt Highs_getInt64InfoValue(const void* highs, const char* info,
                                 int64_t* value);

extern
HighsInt Highs_getInfoType(const void* highs, const char* info, HighsInt* type);

extern
HighsInt Highs_getSolution(const void* highs, double* col_value,
                           double* col_dual, double* row_value,
                           double* row_dual);

extern
HighsInt Highs_getBasis(const void* highs, HighsInt* col_status,
                        HighsInt* row_status);

extern
HighsInt Highs_getModelStatus(const void* highs);

extern
HighsInt Highs_getDualRay(const void* highs, HighsInt* has_dual_ray,
                          double* dual_ray_value);

extern
HighsInt Highs_getPrimalRay(const void* highs, HighsInt* has_primal_ray,
                            double* primal_ray_value);

extern
double Highs_getObjectiveValue(const void* highs);

extern
HighsInt Highs_getBasicVariables(const void* highs, HighsInt* basic_variables);

extern
HighsInt Highs_getBasisInverseRow(const void* highs, const HighsInt row,
                                  double* row_vector, HighsInt* row_num_nz,
                                  HighsInt* row_index);

extern
HighsInt Highs_getBasisInverseCol(const void* highs, const HighsInt col,
                                  double* col_vector, HighsInt* col_num_nz,
                                  HighsInt* col_index);

extern
HighsInt Highs_getBasisSolve(const void* highs, const double* rhs,
                             double* solution_vector, HighsInt* solution_num_nz,
                             HighsInt* solution_index);

extern
HighsInt Highs_getBasisTransposeSolve(const void* highs, const double* rhs,
                                      double* solution_vector,
                                      HighsInt* solution_nz,
                                      HighsInt* solution_index);

extern
HighsInt Highs_getReducedRow(const void* highs, const HighsInt row,
                             double* row_vector, HighsInt* row_num_nz,
                             HighsInt* row_index);

extern
HighsInt Highs_getReducedColumn(const void* highs, const HighsInt col,
                                double* col_vector, HighsInt* col_num_nz,
                                HighsInt* col_index);

extern
HighsInt Highs_setBasis(void* highs, const HighsInt* col_status,
                        const HighsInt* row_status);

extern
HighsInt Highs_setLogicalBasis(void* highs);

extern
HighsInt Highs_setSolution(void* highs, const double* col_value,
                           const double* row_value, const double* col_dual,
                           const double* row_dual);

extern
HighsInt Highs_setCallback(void* highs, HighsCCallbackType user_callback,
                           void* user_callback_data);

extern
HighsInt Highs_startCallback(void* highs, const int callback_type);

extern
HighsInt Highs_stopCallback(void* highs, const int callback_type);

extern
double Highs_getRunTime(const void* highs);

extern
HighsInt Highs_zeroAllClocks(const void* highs);

extern
HighsInt Highs_addCol(void* highs, const double cost, const double lower,
                      const double upper, const HighsInt num_new_nz,
                      const HighsInt* index, const double* value);

extern
HighsInt Highs_addCols(void* highs, const HighsInt num_new_col,
                       const double* costs, const double* lower,
                       const double* upper, const HighsInt num_new_nz,
                       const HighsInt* starts, const HighsInt* index,
                       const double* value);

extern
HighsInt Highs_addVar(void* highs, const double lower, const double upper);

extern
HighsInt Highs_addVars(void* highs, const HighsInt num_new_var,
                       const double* lower, const double* upper);

extern
HighsInt Highs_addRow(void* highs, const double lower, const double upper,
                      const HighsInt num_new_nz, const HighsInt* index,
                      const double* value);

extern
HighsInt Highs_addRows(void* highs, const HighsInt num_new_row,
                       const double* lower, const double* upper,
                       const HighsInt num_new_nz, const HighsInt* starts,
                       const HighsInt* index, const double* value);

extern
HighsInt Highs_changeObjectiveSense(void* highs, const HighsInt sense);

extern
HighsInt Highs_changeObjectiveOffset(void* highs, const double offset);

extern
HighsInt Highs_changeColIntegrality(void* highs, const HighsInt col,
                                    const HighsInt integrality);

extern
HighsInt Highs_changeColsIntegralityByRange(void* highs,
                                            const HighsInt from_col,
                                            const HighsInt to_col,
                                            const HighsInt* integrality);

extern
HighsInt Highs_changeColsIntegralityBySet(void* highs,
                                          const HighsInt num_set_entries,
                                          const HighsInt* set,
                                          const HighsInt* integrality);

extern
HighsInt Highs_changeColsIntegralityByMask(void* highs, const HighsInt* mask,
                                           const HighsInt* integrality);

extern
HighsInt Highs_clearIntegrality(void* highs);

extern
HighsInt Highs_changeColCost(void* highs, const HighsInt col,
                             const double cost);

extern
HighsInt Highs_changeColsCostByRange(void* highs, const HighsInt from_col,
                                     const HighsInt to_col, const double* cost);

extern
HighsInt Highs_changeColsCostBySet(void* highs, const HighsInt num_set_entries,
                                   const HighsInt* set, const double* cost);

extern
HighsInt Highs_changeColsCostByMask(void* highs, const HighsInt* mask,
                                    const double* cost);

extern
HighsInt Highs_changeColBounds(void* highs, const HighsInt col,
                               const double lower, const double upper);

extern
HighsInt Highs_changeColsBoundsByRange(void* highs, const HighsInt from_col,
                                       const HighsInt to_col,
                                       const double* lower,
                                       const double* upper);

extern
HighsInt Highs_changeColsBoundsBySet(void* highs,
                                     const HighsInt num_set_entries,
                                     const HighsInt* set, const double* lower,
                                     const double* upper);

extern
HighsInt Highs_changeColsBoundsByMask(void* highs, const HighsInt* mask,
                                      const double* lower, const double* upper);

extern
HighsInt Highs_changeRowBounds(void* highs, const HighsInt row,
                               const double lower, const double upper);

extern
HighsInt Highs_changeRowsBoundsBySet(void* highs,
                                     const HighsInt num_set_entries,
                                     const HighsInt* set, const double* lower,
                                     const double* upper);

extern
HighsInt Highs_changeRowsBoundsByMask(void* highs, const HighsInt* mask,
                                      const double* lower, const double* upper);

extern
HighsInt Highs_changeCoeff(void* highs, const HighsInt row, const HighsInt col,
                           const double value);

extern
HighsInt Highs_getObjectiveSense(const void* highs, HighsInt* sense);

extern
HighsInt Highs_getObjectiveOffset(const void* highs, double* offset);

extern
HighsInt Highs_getColsByRange(const void* highs, const HighsInt from_col,
                              const HighsInt to_col, HighsInt* num_col,
                              double* costs, double* lower, double* upper,
                              HighsInt* num_nz, HighsInt* matrix_start,
                              HighsInt* matrix_index, double* matrix_value);

extern
HighsInt Highs_getColsBySet(const void* highs, const HighsInt num_set_entries,
                            const HighsInt* set, HighsInt* num_col,
                            double* costs, double* lower, double* upper,
                            HighsInt* num_nz, HighsInt* matrix_start,
                            HighsInt* matrix_index, double* matrix_value);

extern
HighsInt Highs_getColsByMask(const void* highs, const HighsInt* mask,
                             HighsInt* num_col, double* costs, double* lower,
                             double* upper, HighsInt* num_nz,
                             HighsInt* matrix_start, HighsInt* matrix_index,
                             double* matrix_value);

extern
HighsInt Highs_getRowsByRange(const void* highs, const HighsInt from_row,
                              const HighsInt to_row, HighsInt* num_row,
                              double* lower, double* upper, HighsInt* num_nz,
                              HighsInt* matrix_start, HighsInt* matrix_index,
                              double* matrix_value);

extern
HighsInt Highs_getRowsBySet(const void* highs, const HighsInt num_set_entries,
                            const HighsInt* set, HighsInt* num_row,
                            double* lower, double* upper, HighsInt* num_nz,
                            HighsInt* matrix_start, HighsInt* matrix_index,
                            double* matrix_value);

extern
HighsInt Highs_getRowsByMask(const void* highs, const HighsInt* mask,
                             HighsInt* num_row, double* lower, double* upper,
                             HighsInt* num_nz, HighsInt* matrix_start,
                             HighsInt* matrix_index, double* matrix_value);

extern
HighsInt Highs_getRowName(const void* highs, const HighsInt row, char* name);

extern
HighsInt Highs_getRowByName(const void* highs, const char* name, HighsInt* row);

extern
HighsInt Highs_getColName(const void* highs, const HighsInt col, char* name);

extern
HighsInt Highs_getColByName(const void* highs, const char* name, HighsInt* col);

extern
HighsInt Highs_getColIntegrality(const void* highs, const HighsInt col,
                                 HighsInt* integrality);

extern
HighsInt Highs_deleteColsByRange(void* highs, const HighsInt from_col,
                                 const HighsInt to_col);

extern
HighsInt Highs_deleteColsBySet(void* highs, const HighsInt num_set_entries,
                               const HighsInt* set);

extern
HighsInt Highs_deleteColsByMask(void* highs, HighsInt* mask);

extern
HighsInt Highs_deleteRowsByRange(void* highs, const int from_row,
                                 const HighsInt to_row);

extern
HighsInt Highs_deleteRowsBySet(void* highs, const HighsInt num_set_entries,
                               const HighsInt* set);

extern
HighsInt Highs_deleteRowsByMask(void* highs, HighsInt* mask);

extern
HighsInt Highs_scaleCol(void* highs, const HighsInt col, const double scaleval);

extern
HighsInt Highs_scaleRow(void* highs, const HighsInt row, const double scaleval);

extern
double Highs_getInfinity(const void* highs);

extern
HighsInt Highs_getSizeofHighsInt(const void* highs);

extern
HighsInt Highs_getNumCol(const void* highs);

extern
HighsInt Highs_getNumRow(const void* highs);

extern
HighsInt Highs_getNumNz(const void* highs);

extern
HighsInt Highs_getHessianNumNz(const void* highs);

extern
HighsInt Highs_getPresolvedNumCol(const void* highs);

extern
HighsInt Highs_getPresolvedNumRow(const void* highs);

extern
HighsInt Highs_getPresolvedNumNz(const void* highs);

extern
HighsInt Highs_getModel(const void* highs, const HighsInt a_format,
                        const HighsInt q_format, HighsInt* num_col,
                        HighsInt* num_row, HighsInt* num_nz,
                        HighsInt* hessian_num_nz, HighsInt* sense,
                        double* offset, double* col_cost, double* col_lower,
                        double* col_upper, double* row_lower, double* row_upper,
                        HighsInt* a_start, HighsInt* a_index, double* a_value,
                        HighsInt* q_start, HighsInt* q_index, double* q_value,
                        HighsInt* integrality);

extern
HighsInt Highs_getLp(const void* highs, const HighsInt a_format,
                     HighsInt* num_col, HighsInt* num_row, HighsInt* num_nz,
                     HighsInt* sense, double* offset, double* col_cost,
                     double* col_lower, double* col_upper, double* row_lower,
                     double* row_upper, HighsInt* a_start, HighsInt* a_index,
                     double* a_value, HighsInt* integrality);

extern
HighsInt Highs_getPresolvedLp(const void* highs, const HighsInt a_format,
                              HighsInt* num_col, HighsInt* num_row,
                              HighsInt* num_nz, HighsInt* sense, double* offset,
                              double* col_cost, double* col_lower,
                              double* col_upper, double* row_lower,
                              double* row_upper, HighsInt* a_start,
                              HighsInt* a_index, double* a_value,
                              HighsInt* integrality);

extern
HighsInt Highs_crossover(void* highs, const int num_col, const int num_row,
                         const double* col_value, const double* col_dual,
                         const double* row_dual);

extern
HighsInt Highs_getRanging(
    void* highs,

    double* col_cost_up_value, double* col_cost_up_objective,
    HighsInt* col_cost_up_in_var, HighsInt* col_cost_up_ou_var,
    double* col_cost_dn_value, double* col_cost_dn_objective,
    HighsInt* col_cost_dn_in_var, HighsInt* col_cost_dn_ou_var,
    double* col_bound_up_value, double* col_bound_up_objective,
    HighsInt* col_bound_up_in_var, HighsInt* col_bound_up_ou_var,
    double* col_bound_dn_value, double* col_bound_dn_objective,
    HighsInt* col_bound_dn_in_var, HighsInt* col_bound_dn_ou_var,
    double* row_bound_up_value, double* row_bound_up_objective,
    HighsInt* row_bound_up_in_var, HighsInt* row_bound_up_ou_var,
    double* row_bound_dn_value, double* row_bound_dn_objective,
    HighsInt* row_bound_dn_in_var, HighsInt* row_bound_dn_ou_var);

extern
void Highs_resetGlobalScheduler(const HighsInt blocking);

extern
const void* Highs_getCallbackDataOutItem(const HighsCallbackDataOut* data_out,
                                         const char* item_name);

extern
const char* Highs_compilationDate(void);

extern
HighsInt Highs_call(const HighsInt num_col, const HighsInt num_row,
                    const HighsInt num_nz, const double* col_cost,
                    const double* col_lower, const double* col_upper,
                    const double* row_lower, const double* row_upper,
                    const HighsInt* a_start, const HighsInt* a_index,
                    const double* a_value, double* col_value, double* col_dual,
                    double* row_value, double* row_dual,
                    HighsInt* col_basis_status, HighsInt* row_basis_status,
                    HighsInt* model_status);

extern
HighsInt Highs_runQuiet(void* highs);

extern
HighsInt Highs_setHighsLogfile(void* highs, const void* logfile);

extern
HighsInt Highs_setHighsOutput(void* highs, const void* outputfile);

extern
HighsInt Highs_getIterationCount(const void* highs);

extern
HighsInt Highs_getSimplexIterationCount(const void* highs);

extern
HighsInt Highs_setHighsBoolOptionValue(void* highs, const char* option,
                                       const HighsInt value);

extern
HighsInt Highs_setHighsIntOptionValue(void* highs, const char* option,
                                      const HighsInt value);

extern
HighsInt Highs_setHighsDoubleOptionValue(void* highs, const char* option,
                                         const double value);

extern
HighsInt Highs_setHighsStringOptionValue(void* highs, const char* option,
                                         const char* value);

extern
HighsInt Highs_setHighsOptionValue(void* highs, const char* option,
                                   const char* value);

extern
HighsInt Highs_getHighsBoolOptionValue(const void* highs, const char* option,
                                       HighsInt* value);

extern
HighsInt Highs_getHighsIntOptionValue(const void* highs, const char* option,
                                      HighsInt* value);

extern
HighsInt Highs_getHighsDoubleOptionValue(const void* highs, const char* option,
                                         double* value);

extern
HighsInt Highs_getHighsStringOptionValue(const void* highs, const char* option,
                                         char* value);

extern
HighsInt Highs_getHighsOptionType(const void* highs, const char* option,
                                  HighsInt* type);

extern
HighsInt Highs_resetHighsOptions(void* highs);

extern
HighsInt Highs_getHighsIntInfoValue(const void* highs, const char* info,
                                    HighsInt* value);

extern
HighsInt Highs_getHighsDoubleInfoValue(const void* highs, const char* info,
                                       double* value);

extern
HighsInt Highs_getNumCols(const void* highs);

extern
HighsInt Highs_getNumRows(const void* highs);

extern
double Highs_getHighsInfinity(const void* highs);

extern
double Highs_getHighsRunTime(const void* highs);

extern
HighsInt Highs_setOptionValue(void* highs, const char* option,
                              const char* value);

extern
HighsInt Highs_getScaledModelStatus(const void* highs);

#endif
