// Code generated by "stringer -type=ModelStatus"; DO NOT EDIT.

package highs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownModelStatus-0]
	_ = x[NotSet-1]
	_ = x[LoadError-2]
	_ = x[ModelError-3]
	_ = x[PresolveError-4]
	_ = x[SolveError-5]
	_ = x[PostsolveError-6]
	_ = x[ModelEmpty-7]
	_ = x[Optimal-8]
	_ = x[Infeasible-9]
	_ = x[UnboundedOrInfeasible-10]
	_ = x[Unbounded-11]
	_ = x[ObjectiveBound-12]
	_ = x[ObjectiveTarget-13]
	_ = x[TimeLimit-14]
	_ = x[IterationLimit-15]
}

const _ModelStatus_name = "UnknownModelStatusNotSetLoadErrorModelErrorPresolveErrorSolveErrorPostsolveErrorModelEmptyOptimalInfeasibleUnboundedOrInfeasibleUnboundedObjectiveBoundObjectiveTargetTimeLimitIterationLimit"

var _ModelStatus_index = [...]uint8{0, 18, 24, 33, 43, 56, 66, 80, 90, 97, 107, 128, 137, 151, 166, 175, 189}

func (i ModelStatus) String() string {
	if i < 0 || i >= ModelStatus(len(_ModelStatus_index)-1) {
		return "ModelStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModelStatus_name[_ModelStatus_index[i]:_ModelStatus_index[i+1]]
}
