// Code generated by "stringer -type=VariableType"; DO NOT EDIT.

package highs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContinuousType-0]
	_ = x[IntegerType-1]
	_ = x[SemiContinuousType-2]
	_ = x[SemiIntegerType-3]
	_ = x[ImplicitIntegerType-4]
}

const _VariableType_name = "ContinuousTypeIntegerTypeSemiContinuousTypeSemiIntegerTypeImplicitIntegerType"

var _VariableType_index = [...]uint8{0, 14, 25, 43, 58, 77}

func (i VariableType) String() string {
	if i < 0 || i >= VariableType(len(_VariableType_index)-1) {
		return "VariableType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariableType_name[_VariableType_index[i]:_VariableType_index[i+1]]
}
